"""Upding book table

Revision ID: 797c916d0343
Revises: 1d2bdfa0a581
Create Date: 2019-12-15 19:48:47.417109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797c916d0343'
down_revision = '1d2bdfa0a581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('thumbnail', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'thumbnail')
    # ### end Alembic commands ###
